import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function RoutesView() {
    return (_jsxs("div", { className: "relative min-h-[calc(100vh-180px)] overflow-hidden rounded-3xl border border-outline-variant bg-surface-container-lowest shadow-lg", children: [_jsxs("div", { className: "absolute inset-0 z-0 overflow-hidden", children: [_jsx("img", { alt: "Mapa de rutas", src: "https://lh3.googleusercontent.com/aida-public/AB6AXuC82W5E7AhUzpv5NRItDqsX3HQjV2FW1M5wBD180W6Zq9BTg4HGlDBBMpEb6H3EvIb57kWKDMKPtbLw4Z1bkstvQ8xm4aq9KMiNc5LMFdqGp25L4slaCTeZdaSQWabMC1v8NbwLiy_R4OybEQHQcz2zchYrNO_Wcq83ehpROQXi5TNdDxE7wUCqWFCYCz_6cvqc9UyemlWtDb00nh0BRTV24Z6Y0ho7_dUnAwHyAyJTr4BfX1OlWW_3", className: "h-full w-full object-cover" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-br from-surface-container-low/80 via-surface/50 to-surface-container-lowest/70" })] }), _jsxs("div", { className: "relative z-10 flex h-full flex-col gap-md p-margin lg:flex-row", children: [_jsxs("section", { className: "w-full max-w-[420px] rounded-2xl border border-outline-variant/70 bg-surface/90 p-md shadow-lg backdrop-blur-md lg:h-full", children: [_jsxs("div", { className: "mb-md flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h2", { className: "font-headline-lg-mobile text-on-surface", children: "Rutas activas" }), _jsx("p", { className: "text-body-md text-on-surface-variant", children: "Gestionando recolecci\u00F3n en sector sur." })] }), _jsx("span", { className: "rounded-full bg-primary-container px-3 py-1 font-label-sm text-on-primary-container", children: "El Bosque" })] }), _jsx("div", { className: "space-y-2", children: [
                                    {
                                        id: "R-305",
                                        status: "En Tránsito",
                                        statusClass: "bg-tertiary-fixed text-on-tertiary-fixed",
                                        driver: "Carlos Mendoza",
                                        route: "Hacia: Gran Avenida P.30",
                                        eta: "ETA: 12 min",
                                    },
                                    {
                                        id: "R-308",
                                        status: "Cargando",
                                        statusClass: "bg-secondary-container text-on-secondary-container",
                                        driver: "Ana Rojas",
                                        route: "Punto: Alejandro Guzmán 1200",
                                        eta: "ETA: --",
                                    },
                                    {
                                        id: "R-299",
                                        status: "Completada",
                                        statusClass: "bg-surface-variant text-on-surface-variant",
                                        driver: "Luis Torres",
                                        route: "Sector: Padre Hurtado Sur",
                                        eta: "14:30",
                                    },
                                ].map((route) => (_jsxs("div", { className: "rounded-xl border border-outline-variant/60 bg-surface-container-lowest p-4 shadow-sm", children: [_jsxs("div", { className: "mb-2 flex items-start justify-between gap-2", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "font-label-sm text-on-surface", children: route.id }), _jsx("span", { className: `rounded-full px-2 py-0.5 text-[10px] font-label-sm ${route.statusClass}`, children: route.status })] }), _jsx("span", { className: "font-label-sm text-on-surface-variant", children: route.eta })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-surface-container", children: _jsx("span", { className: "material-symbols-outlined text-[16px]", children: "person" }) }), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsx("p", { className: "truncate font-label-sm text-on-surface", children: route.driver }), _jsx("p", { className: "truncate text-[13px] text-on-surface-variant", children: route.route })] })] })] }, route.id))) })] }), _jsx("section", { className: "flex-1", children: _jsxs("div", { className: "ml-auto flex max-w-[320px] flex-col gap-md rounded-2xl border border-outline-variant/70 bg-surface/90 p-md shadow-lg backdrop-blur-md", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h3", { className: "font-label-sm uppercase tracking-wider text-on-surface-variant", children: "Estado de flota" }), _jsx("span", { className: "material-symbols-outlined text-primary", children: "speed" })] }), _jsxs("div", { className: "flex items-end gap-2", children: [_jsx("span", { className: "font-display-lg tracking-tighter text-primary", children: "92" }), _jsx("span", { className: "mb-2 font-headline-lg text-primary", children: "%" })] }), _jsx("p", { className: "-mt-2 text-body-md text-on-surface-variant", children: "Eficiencia operativa hoy" }), _jsxs("div", { className: "mt-2 flex gap-2", children: [_jsxs("div", { className: "flex flex-1 flex-col items-center justify-center rounded-xl bg-surface-container p-3", children: [_jsx("span", { className: "font-headline-lg text-on-surface", children: "8" }), _jsx("span", { className: "text-center text-[10px] font-label-sm text-on-surface-variant", children: "Activos" })] }), _jsxs("div", { className: "flex flex-1 flex-col items-center justify-center rounded-xl bg-error-container p-3", children: [_jsx("span", { className: "font-headline-lg text-on-error-container", children: "2" }), _jsx("span", { className: "text-center text-[10px] font-label-sm text-on-error-container", children: "Mantenimiento" })] })] })] }) })] })] }));
}
