import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function DashboardShell({ appName, panelTitle, subtitle, username, roleLabel, navItems, topTabs, activeTopTab, ctaLabel, onTopTabChange, onLogout, children, }) {
    return (_jsxs("div", { className: "flex min-h-screen bg-background text-on-surface", children: [_jsxs("aside", { className: "fixed left-0 top-0 hidden h-screen w-[280px] flex-col border-r border-outline-variant bg-surface-container-low py-md md:flex", children: [_jsxs("div", { className: "mb-lg px-md", children: [_jsx("h1", { className: "font-headline-lg-mobile font-black text-primary", children: appName }), _jsx("p", { className: "mt-1 text-label-sm uppercase tracking-widest text-on-surface-variant", children: panelTitle })] }), _jsx("nav", { className: "flex flex-1 flex-col px-2", children: navItems.map((item) => (_jsxs("button", { type: "button", onClick: item.onClick, className: `mb-1 flex items-center gap-3 rounded-lg px-4 py-3 text-left transition-all ${item.active
                                ? "bg-secondary-container text-on-secondary-container"
                                : "text-on-surface-variant hover:bg-surface-container-highest"}`, children: [_jsx("span", { className: "material-symbols-outlined", children: item.icon }), _jsx("span", { className: "font-label-sm text-label-sm", children: item.label })] }, item.label))) }), _jsxs("div", { className: "mt-auto border-t border-outline-variant px-md pt-md", children: [ctaLabel && (_jsxs("button", { type: "button", className: "mb-4 flex w-full items-center justify-center gap-2 rounded-xl bg-primary py-3 font-label-sm text-label-sm text-on-primary transition-all hover:opacity-90 active:scale-[0.98]", children: [_jsx("span", { className: "material-symbols-outlined", children: "add" }), ctaLabel] })), _jsxs("button", { type: "button", onClick: onLogout, className: "flex w-full items-center justify-center gap-2 rounded-lg border border-error py-2 font-label-sm text-error transition-colors hover:bg-error/5", children: [_jsx("span", { className: "material-symbols-outlined", children: "logout" }), "Cerrar Sesion"] })] })] }), _jsxs("main", { className: "flex min-h-screen flex-1 flex-col md:ml-[280px]", children: [_jsxs("header", { className: "sticky top-0 z-30 flex h-20 items-center justify-between border-b border-outline-variant bg-surface-container-lowest px-margin shadow-sm", children: [_jsxs("div", { children: [_jsx("h2", { className: "font-headline-lg-mobile text-on-surface", children: panelTitle }), _jsx("p", { className: "text-body-md text-on-surface-variant", children: subtitle })] }), _jsx("div", { className: "hidden items-center gap-6 md:flex", children: topTabs &&
                                    topTabs.map((tab) => (_jsx("button", { type: "button", onClick: () => onTopTabChange?.(tab), className: `pb-1 text-body-md transition-colors ${tab === activeTopTab
                                            ? "border-b-2 border-secondary font-bold text-secondary"
                                            : "text-on-surface-variant hover:text-secondary"}`, children: tab }, tab))) }), _jsxs("div", { className: "flex items-center gap-md", children: [_jsx("button", { type: "button", className: "rounded-full p-2 text-on-surface-variant transition-colors hover:bg-surface-container", children: _jsx("span", { className: "material-symbols-outlined", children: "notifications" }) }), _jsx("button", { type: "button", className: "hidden rounded-full p-2 text-on-surface-variant transition-colors hover:bg-surface-container sm:block", children: _jsx("span", { className: "material-symbols-outlined", children: "help" }) }), _jsxs("div", { className: "flex items-center gap-sm border-l border-outline-variant pl-md", children: [_jsxs("div", { className: "hidden text-right sm:block", children: [_jsx("p", { className: "font-label-sm font-bold text-on-surface", children: username }), _jsx("p", { className: "text-[10px] text-on-surface-variant", children: roleLabel })] }), _jsx("div", { className: "flex h-10 w-10 items-center justify-center rounded-full bg-surface-container text-primary", children: _jsx("span", { className: "material-symbols-outlined", children: "person" }) })] })] })] }), _jsx("section", { className: "flex-1 p-margin", children: children })] })] }));
}
